### ISSUE TITLE
Footer to show menus of site-map

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#10]
E.g. as per https://www.wearequeeraf.com/

<img width="838" alt="Screenshot 2023-08-03 at 15 37 23" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/de058772-e3d7-4688-a8f1-1ff478f238e1">

**Comment by peterfremlin** [comment]
Currently the font-size on footer is a bit small, should be closer to the size on the page.

I will adjust the menu as I go. No need for it to include social media necessarily, whatever you think is good presentation.

Initial headers are:

*About*
Accessibility
What they say
Sign-up

*Library*
Backcatalogue
Subjects
Countries
Highlights

*Climate*

*Support*

*Contact*

**Comment by cathysarisky** [comment]
OK, so to use this item, you need a page with the slug 'footer-content'.  Create headers as H3s (the smaller option in the editor), and make lists (start the line with * to get it into list mode) below any header that has list items.

Other inclusions beyond h3 and lists not tested, but any div marked 'footer-nav-section' will probably work as long as it doesn't have any horribly wide content in it.

This in the editor: 
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/db611ae2-2bb6-4b9a-9fed-40fafe550114)

Produces this in the browser:
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/cf8ee1d3-d41a-425a-bacc-f78e3774c531)

Phone version:
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/05dd549e-f359-4a95-83d3-c7764d257b36)

**Comment by peterfremlin** [comment]
Thanks, it's almost there, just some notes on styling, please -

- make less gap between each item vertically
- prefer less horizontal space between each column
- please align centrally
- see if wrapping can be done more economically

Aligned to left, rather than centrally:
<img width="1404" alt="Screenshot 2023-09-08 at 12 30 34" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/dbc47ddf-9445-469e-851e-d7366687e755">

Wrapping of header item contact would be better directly under support

<img width="835" alt="Screenshot 2023-09-08 at 12 30 47" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/bca5973b-c7d4-475a-b2ea-3ee463755bee">

Sample header I used

[About](/about/)
[Accessibility](/accessibility/)
[What they say](/testimonials/)
[Sign-up](/sign-up/)
Library 
Subjects
Countries
Climate
Support
Contact

**Comment by cathysarisky** [comment]
I gave you that much vertical spacing to make it more accessible for touch screen users.  I can close it up if you like.
Working on the rest...

**Comment by cathysarisky** [comment]
The Contact item /should/ be in the right spot... it is on my demo setup.  Ahha.  Add a blank line after it, and I think it'll end up in the right spot!

**Comment by cathysarisky** [comment]
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/fd3679c5-0b21-4074-b8e2-c68f6a223758)

**Comment by peterfremlin** [comment]
Yes it was the returns after the last item, thanks.

And good to know about that distance between items, I hadn't thought of that :)
