### ISSUE TITLE
Adjust subtitles on homepage

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#15]
<img width="1117" alt="Screenshot 2023-08-03 at 16 06 24" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/53667621-5bcb-49d3-a89a-2a921e8b0974">

A second title above the list of articles.

Probably prettier to centre both "recent newsletters" and the second title?

**Comment by cathysarisky** [comment]
What should the text of this header be?

**Comment by peterfremlin** [comment]
That's great. I will adjust the header myself.
