### ISSUE TITLE
A nicer visual presentation of endorsements

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#16]
For instance as in this page:
https://www.disabilitydebrief.org/about/#what-they-say

<img width="699" alt="Screenshot 2023-08-09 at 11 55 15" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/0a5b03ed-190d-44df-b637-72a030cb2749">

The information doesn't pop-out, but I'm not sure what would be a good visual improvement?

**Comment by cathysarisky** [comment]
You might use callout cards (built in, so easy), or you could build them as product cards and I could style them for you.  Here's an example: https://drashti.com/ (scroll down to testimonials).  I'm not a fan of auto scroll, but maybe this at least gives you an example for styling.

**Comment by cathysarisky** [comment]
I'm not sure what you decided for this, so haven't added any styling. Are you using plain call-outs, or do you need a re-style?  If so, what?

**Comment by peterfremlin** [comment]
I will look at with the built-in styling...
