### ISSUE TITLE
Template with a smaller feature image.

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#18]
I will have some pages - like the new author pages, say - where there will be an image, but I don't want it to be as wide as the text. Am thinking about half the size of the current image?

For example, I will add this image to the covid topic page and it doesn't make sense to have it as the size of the regular images. 

![ WhatsApp Image 2023-08-03 at 09 12 Background Removed 55](https://github.com/peterfremlin/Disability-Debrief/assets/106767665/139544c3-93aa-44bc-8da6-fb72a781fc4e)

**Comment by cathysarisky** [comment]
Smaller version added.  Let me know if not small enough?
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/c7aa78b1-5fc4-4b29-ad90-f446e2128d18)

**Comment by peterfremlin** [comment]
In fact I see from this that with the smaller image it will make sense above the title, rather than below. And yes, a bit smaller (like 66% size of present) will be good please

**Comment by cathysarisky** [comment]
Do you want the image above all the header stuff, or just above the title (with author and date above it) ?

**Comment by peterfremlin** [comment]
Above all the header stuff

**Comment by cathysarisky** [comment]
OK, that's what I had in the last (and current too) version.  Not making additional changes now unless you let me know something needs it.

**Comment by peterfremlin** [comment]
On the narrow-feature-image tempalate picture is currently below the page title, and I would like it above the page title please

Currently:

<img width="712" alt="Screenshot 2023-09-08 at 12 59 18" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/1e47964e-02dd-44f4-86b2-fde894ff0943">

**Comment by cathysarisky** [comment]
There's a 'narrow' page template that was already in your theme, and I added a 'small' page template, that does have the rearrangement you want.  Do you want me to switch narrow to behave just like small?

**Comment by cathysarisky** [comment]
I've switched the author page to use the 'small' layout.  I think that's a better fit.

**Comment by peterfremlin** [comment]
Oh my confusion, sorry. Small is a great fit for author page.

But can you remove the Date and narrow whitespace between the picture and the heading?

**Comment by cathysarisky** [comment]
Yes. Do you want it removed from all small templates or just author?Sent from my iPhoneOn Sep 11, 2023, at 8:27 AM, peterfremlin ***@***.***> wrote:﻿
Oh my confusion, sorry. Small is a great fit for author page.
But can you remove the Date and narrow whitespace between the picture and the heading?

**Comment by cathysarisky** [comment]
completed

**Comment by peterfremlin** [comment]
Thanks but there is still a lot of whitespace?

<img width="564" alt="Screenshot 2023-09-12 at 11 26 34" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/76463f58-f7f6-4b98-ac3d-efc0721571a2">

**Comment by cathysarisky** [comment]
Will check it!Sent from my iPhoneOn Sep 12, 2023, at 6:28 AM, peterfremlin ***@***.***> wrote:﻿
Thanks but there is still a lot of whitespace?
