### ISSUE TITLE
Mouse-over to get link to headers

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#19]
Mouse-over on h2, h3, h4 to show something you can press to get a direct link to that section

eg like substack does it on newsletters
or how it's done on plausible https://plausible.io/docs/troubleshoot-integration

**Comment by cathysarisky** [comment]
added

**Comment by peterfremlin** [comment]
Looking good, just some finesse:

- clicking on it should also copy the link to the clipboard
- ideally it would be the same colour as the heading title (I think this will always be black)

The # is turning up in places that it doesn't belong
- on the headers used for lists of articles (e.g. on home page it turns up on "articles")
- on kg-signup-card-subheading class for the ghost sign-up embed
- on the new library pages, after selecting/unselecting different items, all the headings show "#"  next to them before mouse-over

**Comment by cathysarisky** [comment]
Whoops! Will fix!Sent from my iPhoneOn Sep 4, 2023, at 7:32 AM, peterfremlin ***@***.***> wrote:﻿
Looking good, just some finesse:

clicking on it should also copy the link to the clipboard
ideally it would be the same colour as the heading title (I think this will always be black)

The # is turning up in places that it doesn't belong

on the headers used for lists of articles (e.g. on home page it turns up on "articles")
on kg-signup-card-subheading class for the ghost sign-up embed
on the new library pages, after selecting/unselecting different items, all the headings show "#"  next to them before mouse-over

**Comment by cathysarisky** [comment]
Added check mark for visual feedback on click.  Fixed color.  Made more selective what titles get tagged.  Added copy to clipboard.
I've turned off the # for all of the datadebrief pages.  Is that the desired behavior?

**Comment by peterfremlin** [comment]
Sounds like very nearly there. Keep it on for the databrief pages as it's needed there (the issue was when selecting/unselecting using the filters, that the # became visible without mouseover)

**Comment by cathysarisky** [comment]
Got it.  Adjusted.

**Comment by peterfremlin** [comment]
Nicely done, thanks! I don't know how much my readers will use but this makes life a lot easier for me immediately :) And nice touch with the tick.
