### ISSUE TITLE
tag/author page slug

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#20]
Sorry to come back on this, a slight change

Basically sometimes I would like to use /{slug}  as the page for a tag page. E.g. I want to make a climate page that is /climate and shows the contents of /tags/climate

Would it be possible to go back to your original setting, that the author and tag pages come directly {slug} and add a condition that it only does that if those slugs are tag and author templates respectively?

Thanks!

**Comment by cathysarisky** [comment]
The /author/peter and /tag/climate links are sort of throughout the whole theme.  I'm a little worried about hunting down every occurrence if you're looking to launch early next week.

A better option might be to use routes.yaml to cause /climate to serve the /tag/climate page.
