### ISSUE TITLE
Wrapping of titles on pagination

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#21]
Titles that go over two lines have an excessive gap

eg the one on mental health: 

<img width="716" alt="Screenshot 2023-09-11 at 15 38 32" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/ad7ca01d-6cfb-4026-a6b9-466c8325a17c">

**Comment by cathysarisky** [comment]
Completed.

**Comment by peterfremlin** [comment]
Lovely!
