### ISSUE TITLE
Keyboard focus pagination

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#22]
Part of accessibility is keyboard navigability - there is a thin line on the left that's visible on tabbing through paginated article list, and it would be nicer if that was the primary theme colour (and if easy to do, a box around it) as per other keyboard focus

**Comment by cathysarisky** [comment]
Which template? Or all of them?

**Comment by peterfremlin** [comment]
Again, sorry, by pagination I mean on the list of articles. (Trying tabbing through the home page and you will see how other elements are highlighted vs the article list)

Theme is live at https://www.disabilitydebrief.org/

**Comment by peterfremlin** [comment]
Tab index much improved! great to see
