### ISSUE TITLE
Pagination: remove arrows on mouse-over

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#23]
(result of an access check)

Currently, mouse-over on articles in pagination display a small arrow to the right. (This was already in the theme before these changes).

It doesn't add much visually and it does cause some confusion for a screen reader.

Can you remove it please?

**Comment by cathysarisky** [comment]
Can do!

**Comment by cathysarisky** [comment]
Removed.  And then I discovered there was some javascript attached.  Fixing!

**Comment by cathysarisky** [comment]
Done.  Went along with fixing the tab navigation, etc.
