### ISSUE TITLE
Pagination: link on article heading

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#24]
(result of an access check)

Currently for a screenreader, the header, is read out and then after the subheader/image, the link is read out, which has the same title as the header.

If the link can be put on the header itself, that will make it more efficient.

**Comment by cathysarisky** [comment]
Adjustments made, also made the date come 'after' (for screenreaders) the title, which I thought improved meaning.

**Comment by peterfremlin** [comment]
Super!
