### ISSUE TITLE
Pagination: order of date

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#25]
(result of an access check). 

This is a fairly minor issue, so only if there's an easy fix.

(Visually it is totally fine and should stay as is)

Currently screenreaders are read the date, and then the heading that corresponds. 

It would make more sense if the date came after the heading that corresponds.

**Comment by cathysarisky** [comment]
Can you tell me specifically which page this is happening on?

**Comment by cathysarisky** [comment]
I now have it reading title (which is also a link), then excerpt, then link, then image.

**Comment by peterfremlin** [comment]
Perfect!
