### ISSUE TITLE
Bug in link click on pagination

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#27]
When I control-click on an article in the paginated list, it should open in a new window (and does), but it also opens in the existing window

**Comment by cathysarisky** [comment]
I went to get this resolved today and am not sure I'm experiencing it.  Can you point me at a specific page and link that has this behavior?  First step is always seeing it, THEN squashing the bug...

**Comment by peterfremlin** [comment]
(this is the homepage, it's the same on the others)
