### ISSUE TITLE
Search: presentation

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#34]
- [x] title should be in line with other page titles
--- meaning that you want it aligned the same way?  Or the same (larger) styling?
- [x] I would like to add some text at the top of the page (and be able to adjust this) 
--- no problem.  See comment below.
- [x] the paging buttons at the bottom of each section (Page 1, 2, 3) are too small, and the colour is low contrast
- [x] Clear filters button

A select-none button for both topics and countries?

- [x] Filtering by categories with lots of results should have a preview/expand

For instance if I want Africa:
<img width="285" alt="Screenshot 2024-03-29 at 18 52 50" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/14782e17-675a-495f-ba55-898368d93aa3">

Perhaps better to have only some countries shown and the rest hidden under "see more"

- [x] adjust country/category display on library results

Currently shows Africa -> Uganda. Can change just to the country name, and make it clickable? Will also be good to have the topic name, and make it clickable. (They can go to that specific section on the respective pages)

Assume that the colour contrast of those tags is checked re accessibility

**Comment by cathysarisky** [comment]
_"Currently shows Africa -> Uganda. Can change just to the country name, and make it clickable?"_ - so you'd like it to say "Uganda" and "Mali", without continent shown, correct?

_"Will also be good to have the topic name, and make it clickable."_ - are you asking for a change in how topics are displayed, too?  Not sure I'm parsing this.

**Comment by cathysarisky** [comment]
Question about items 1&2.  Currently this page is a LOT wider than other pages. Here's an example other page
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/882e3fd3-73ae-4a06-9c7d-20fcb73a19cc)

And here's the search page:
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/03a4a843-8cc1-4340-927f-9cf9ed4f0b86)

I can make the top section (with your text) look like the other pages - narrower, centered title, etc, but then the actual search section is going to be quite a bit wider.  Good with that?

**Comment by peterfremlin** [comment]
Yes, it should just show "Mali" rather than "Africa > Mali".

Perhaps I was asking for a tag for topics but that's not a priority atm so actually no action needed on that.

In terms of width, yes the centered title will be good

**Comment by cathysarisky** [comment]
"Currently shows Africa -> Uganda. Can change just to the country name, and make it clickable?"
Have changed to country name on the filters.  Could also do the pages listing, if wanted.  (Do you want?)
I cshouldn't make the country name clickable in a way that takes you somewhere, because clicking it checks the box, and that's what it should do, in terms of expected UI and accessibility.

**Comment by peterfremlin** [comment]
Ah sorry to clarify where I wanted the change to country display - I meant in the tag displayed next to each library result

e.g. here to display just "New Zealand"

<img width="616" alt="Screenshot 2024-04-25 at 13 07 18" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/bf0da281-bf84-430e-9b4e-44c712fa8931">

Would clicking there be expected to adjust the filter result? for me it would be expected to go to the page

**Comment by cathysarisky** [comment]
It currently does neither.  It can do whatever you'd like it to.

**Comment by peterfremlin** [comment]
Yes please, this is what I meant by the point "adjust country/category display on library results"
