### ISSUE TITLE
Whitespace after title (I think due to the # link)

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#35]
Can you check this page https://www.disabilitydebrief.org/debrief/fractured-fighting-fixed/

I think the whitespace here is because of the #

**It appears like this:** 

<img width="693" alt="Screenshot 2024-03-29 at 23 29 10" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/46a0c93d-f274-410d-be17-6a454432588a">

**On mouseover:**

<img width="683" alt="Screenshot 2024-03-29 at 23 29 05" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/245d3e64-afbc-4062-9568-b93b775d94af">

**Comment by cathysarisky** [comment]
Can be corrected with code injection (sitewide).  Insert the following between style tags:

```
a.hover-anchor { 
  position: absolute;
}
```

**Comment by cathysarisky** [comment]
Closing - please reopen if code injection doesn't resolve this, @peterfremlin

**Comment by peterfremlin** [comment]
That fixes it, thanks!

Sorry to be a pedant tho - it also makes the # very close to the title, would appreciate if you can make a bit of whitespace after as it was before

<img width="418" alt="Screenshot 2024-04-25 at 13 02 37" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/501d16db-dcef-4e3f-842d-f37931a6de5a">

**Comment by peterfremlin** [comment]
And if you can include the style in the theme itself that's better that site-wide injection please

**Comment by cathysarisky** [comment]
OK, sure.  Adding to theme.  If you want it tweaked in the meantime, add a margin-left: 1rem;

:)

**Comment by cathysarisky** [comment]
theme edited.
