### ISSUE TITLE
Put search filters on ice

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#38]
Filter search is going to be hard to understand that don't know how the data is organised. And in practice it's not relevant for folk, as you can get to the same results more intuitively by going through the search bar.

So let's hide the buttons from public view. If we put in instead some secret keywords for me (will list these in a separate issue)

- [x] remove "add to filters"
- [x] remove "search filters"
- [x] Reformat the page layout

Without the search filters box, the search button and results can all be centred in the page?

**Comment by cathysarisky** [comment]
added a toggle (ctrl-shift-F) to make the search filters appear.
