### ISSUE TITLE
Sign-up box on homepage

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#4]
<img width="769" alt="Screenshot 2023-08-03 at 16 08 26" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/cb0157bd-9975-43ad-b202-fe0bbc9957fe">

In place of the button, it should have a box where people can put email address.

For example https://ghost.org/themes/edition/

This is in partials/cover.hbs.

### Tasks
- [ ] Check Edition subscribe form for accessibility
- [ ] Adapt box into Debrief theme

**Comment by cathysarisky** [comment]
Can do.  And we'll suppress showing it for signed-in users, right?

**Comment by cathysarisky** [comment]
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/544f494d-b269-46b6-8ad9-22e3493034b7)

**Comment by peterfremlin** [comment]
- The email box is very wide
- if possible to style the subscribe button as per the styling on the ghost sign-up embed, that's preferred for consistency 

eg styling as per subscribe on latest post https://www.disabilitydebrief.org/debrief/sailing-away/
<img width="112" alt="Screenshot 2023-08-29 at 15 59 12" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/dadfdac3-083e-4a69-a081-53abf6559197">

**Comment by peterfremlin** [comment]
Will need to do an access check of this which I can only confirm when uploaded to live site

**Comment by peterfremlin** [comment]
Was checking some of the usability of the sign-up box before going live. I should have said a bit more as this has been a bit fiddly for us. When we tested some of the Ghost options we found their new embed in the beta editor was the most informative and accessible.

So could you use the same code as for the beta editor embed? *not their ghost embed for external sites, which isn't as good*. We don't need the styling, we just need the subscription box.

**Comment by cathysarisky** [comment]
Have switched code.  I removed the blue box and extra text, but kept the sign-up box exactly like the lexical editor's sign-up card.

**Comment by peterfremlin** [comment]
Thanks! It's not rendering the responses correctly. For instance, here's what I get when it gives an error on signup:

<img width="454" alt="Screenshot 2023-09-08 at 12 04 13" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/74275c3b-326e-45c6-a12f-23ae749bf063">

**Comment by cathysarisky** [comment]
Weird. Might be a screen size issue, because it looked OK on my test setup yesterday. Trying to reproduce!

**Comment by peterfremlin** [comment]
oh! I was using Arc but it's same issue on Safari for me

**Comment by cathysarisky** [comment]
Well, we want it to look good on all browsers!Sent from my iPhoneOn Sep 8, 2023, at 12:07 PM, peterfremlin ***@***.***> wrote:﻿
oh! I was using Arc but it's same issue on Safari for me

**Comment by cathysarisky** [comment]
Ahha. Found it.

**Comment by peterfremlin** [comment]
Thanks!
