### ISSUE TITLE
Author page template

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#5]
A page template that will list the posts of the author underneath the page text.

(i.e. so that the author profile can be changed in the editor).

**Comment by cathysarisky** [comment]
Can do.  Looks like the current author page?  Does it pull the author's social links and other data from the author page, or will you set that all up in the editor?

**Comment by peterfremlin** [comment]
Like the tag page, set it all up in editor.

**Comment by cathysarisky** [comment]
OK.  All set up.  You'll need to set up a page (not post) with the exact same slug as the author in order for the content to be pulled in.  (Otherwise, it defaults back to as it was.)

**Comment by peterfremlin** [comment]
Nice solution. I guess my only slight wonder is about what happens if someone goes to /peter rather than /author/peter? Any recommendation on a solution to remove that edge case?

**Comment by cathysarisky** [comment]
Good point.  I can create an 'author' template that you can apply to the
page, that pulls the same content as the /author/peter page does.

**Comment by cathysarisky** [comment]
Have adjusted the author page to look for author-something instead of just something as a page slug.  Have added a "author page" custom template that you can assign to these tag pages that'll automatically redirect the user to the correct page, in case they get there on accident.

**Comment by cathysarisky** [comment]
@peterfremlin , I believe this item is done.  Please let me know if I missed something.
