### ISSUE TITLE
Tag page template

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#6]
A page template that will list the posts of the primary tag under the page text.

(i.e. so that the tag page can be changed in the editor).

**Comment by cathysarisky** [comment]
Sure.  Can be doe either by matching the page slug to the tag slug, OR by applying the tag to the page.  Your choice of options - the second one may be less fiddly, and gives you the option to have two tags show up together.

Do you want the existing styling for a tag page, just with the extra page content (using Dawn's existing styles) at the top, or something else?

Do you want the tag description displayed somewhere?  What about the tag name, or will you use the page title?

**Comment by peterfremlin** [comment]
I think your first question is about way to set it up with routes/etc.

On the styling question, I don't love the existing styling of a tag page, and I don't need tag description/title as essentially I would be making that page content. I think I want a regular page styling that I can totally adjust in the editor, then the posts underneath.

**Comment by cathysarisky** [comment]
Got it. I was asking if the way the posts at the bottom should look matches something on the site already. :)

**Comment by cathysarisky** [comment]
Done. See directions about author page setup.

**Comment by peterfremlin** [comment]
Nice solution.

However the tags could easily have a page named by that by accident, so rather than defaulting to /{slug} can it check the page /tag-{slug} and load from there

**Comment by cathysarisky** [comment]
Absolutely, no problem.

**Comment by cathysarisky** [comment]
Title added (in the HBS for both tag and author pages).  

It's the same font, but a bit smaller.  To my eye, the clash is coming from the difference in margin.  Here's a tweak that makes the feed match the content margin:

![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/bdbf41fa-229b-4223-bc9c-8480e5b55dcb)
What do you think about that?  I can make the fonts be the same size, but then the feed section will definitely need to be wider to accommodate larger text.

**Comment by cathysarisky** [comment]
Have adjusted the tag page to look for tag-something instead of just something as a page slug.  Have added a "tag page" custom template that you can assign to these tag pages that'll automatically redirect the user to the correct page, in case they get there on accident.

**Comment by cathysarisky** [comment]
adjusted. Tags and authors.

**Comment by cathysarisky** [comment]
Oops, still looking at the h2 question.
Here's the default h2 styling.  Is this what you had in mind?
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/62c119af-9bd8-4ccd-979b-8bda142737f0)

**Comment by peterfremlin** [comment]
There is a different styling of the h2 in gh-content. But I think the solution is for me to make the title in the editor, rather than the template, as that will let me adjust things as necessary and change the titles for different pages.

The thing to do is to reduce the spacing between the list of articles and the text of the editor, so it can come with a natural space after an h2 made in the editor.

**Comment by cathysarisky** [comment]
Doing this for tags now.  Do you want the authors page the same way?  Or just better match gh-content h2 and keep it hard-coded as "articles"?

**Comment by cathysarisky** [comment]
Label created at the end of the tag-tagslug page, as an H2.  I also added two carriage returns before the h2.

![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/50a256a7-57dc-4e4d-89ce-b9b00a71adf5)

**Comment by peterfremlin** [comment]
Do the same for authors please

**Comment by cathysarisky** [comment]
completed.
