### ISSUE TITLE
Fix paragraph spacing issue

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#7]
There is too much space before/after Ghost cards.

For instance, here is what it looks like for a logged in user when the sign-up form is not visible. 

<img width="654" alt="Screenshot 2023-08-03 at 14 59 49" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/3ad24ac3-a3ab-44a3-8c13-f44c4fe26d38">

here it is for a logged out user 

<img width="747" alt="Screenshot 2023-08-03 at 14 59 32" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/5eb6ccfa-fa41-44c0-bcf0-fbecfb27ea07">

I probably used less spacing than the official Dawn theme.

Response from Ghost Support:

> I noticed that you run a custom version of Dawn with much less spacing between paragraphs than the default. I also noticed that the official version of Dawn doesn't have this spacing problem. 
> 
> The way that the styling for spacing has been written in your version of Dawn means that you'll get this extra spacing between a paragraph and any of the editor's cards—the signup form, an image, or video, or any other card you choose to add.
> 
> The CSS applies a margin to the top of any HTML block that comes directly after a div with the ".kg-card" class, which isn't itself a div with the ".kg-card" class.
> 
> Could you look at the styling and apply a rule that will close the spacing up in this context?
> 
> There are many ways to do this. The most inelegant but simplest would be this:
> 
> div.kg-signup-card[style*="display: none;"] + p {
> margin-top: 10px !important;
> }
> 
> This gives 10px (a value I picked up from your other spacing rules) of top margin and will try to overwrite any other rules. It will apply to a paragraph if it comes after a sign-up card, if the sign-up card has been hidden with "display:none;"—i.e. it won't apply when the card is visible, as it seems like you liked that spacing.

**Comment by cathysarisky** [comment]
No problem, easy fix.

**Comment by cathysarisky** [comment]
Closed the gap when the sign-up is hidden.  Did you also want smaller gap when the card is visible?

**Comment by peterfremlin** [comment]
yes please!

**Comment by cathysarisky** [comment]
Too small?
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/c0927b46-6f50-4b7c-9756-b57ff0c8d788)
