### ISSUE TITLE
Visual demarcation between links in library

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#8]
Some links in the library are one paragraph, some multiple paragraphs.

<img width="713" alt="Screenshot 2023-08-03 at 15 04 33" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/a89f6b07-b6b4-419e-b9ed-d33972ecf68d">

Good to add styling to show divisions between links. Only needed if there is another link below, not if there is a section below. Best not to use \<hr\> as that creates burden for screenreaders (so a visual-only solution)

**Comment by peterfremlin** [comment]
I was thinking something like an <hr> created by a bottom border on <p> tags? I can mark each individual link as a <div> of a certain class?

**Comment by cathysarisky** [comment]
Sure, if you put a div around each link section, then I'd just put a bottom border on that div.  This is something you're generating, right?  So I just need to add the styling to the theme?

**Comment by peterfremlin** [comment]
Yes that's great. Div would be called "databrief-link" and I would love a horizontal line, centered, maybe 50% width?

**Comment by peterfremlin** [comment]
Half the width of the content sorry

**Comment by cathysarisky** [comment]
[image: image.png]

Style needed (just capturing it here until I'm ready to edit your theme):

   1. border-image-source: radial-gradient(circle, rgba(189,183,183,1) 0%,
   rgba(189,183,183,1) 50%, rgba(255,255,255,1) 50%);
   2. border-image-slice: 1;
   3. border-style: none none solid;
   4. border-width:
   1px
   ;
   5. padding-bottom:
   16px
   ;
   6. margin-bottom:
   16px
   ;

**Comment by peterfremlin** [comment]
Is this in the theme?

**Comment by cathysarisky** [comment]
It is now. :)

**Comment by cathysarisky** [comment]
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/7dadb81e-2cf5-4ec9-96ee-2dd48da21600)

**Comment by cathysarisky** [comment]
Text appears strictly when there are two .databrief-link divs adjacent.

**Comment by peterfremlin** [comment]
Nicely done! Exactly what I asked for.
