### ISSUE TITLE
Presentation of subscription options

### ISSUE THREAD

**Issue by peterfremlin** [peterfremlin/Disability-Debrief#9]
Current presentation of three different tiers on /support/

<img width="672" alt="Screenshot 2023-08-03 at 15 26 51" src="https://github.com/peterfremlin/Disability-Debrief/assets/106767665/0bf6b88a-8b5d-428c-b837-cb5e22e39b93">

It would be nice to have three buttons in one line with the monthly amounts

i.e. html code for three buttons

**Comment by cathysarisky** [comment]
If they're not subscribed, should pop up this page? https://www.disabilitydebrief.org/support/
If they are already subscribed, trigger the Stripe page?

So it'd be like [Using (price) to represent a button.]
Subscription:  
   Monthly ($5) ( $10 ) ( $20 )
   Annually ( $5 ) ( $10 ) ( $20 )

**Comment by peterfremlin** [comment]
Not quite sure what you meant by pop-up that page?

I was imagining 3 buttons in one line, I can't fully visualise what you're suggesting.

Custom donation I am probably going to get something directly on the page, working on that :)

**Comment by cathysarisky** [comment]
Sorry - bad link.  I meant should it open up the portal pop up?

**Comment by peterfremlin** [comment]
I don't love the main portal page for this purpose. Supporters get no benefits, so it's a question of them choosing a number, and they don't need more info. But yes, then clicking on the amount should take them into the portal page of signing up for that amount.

**Comment by cathysarisky** [comment]
Right, can do.

**Comment by cathysarisky** [comment]
Like this?
![image](https://github.com/peterfremlin/Disability-Debrief/assets/42299862/44219af5-ce00-459b-a92a-d8ad821b0779)

If so, put this in an HTML card:
`<ul>
    <li>Subscription</li>
    <ul>
    <li>Monthly at <a  href="#/portal/signup/64ebbbe882217a72f7723c29/monthly" class="price">£5</a> <a href="#/portal/signup/64ebbbe882217a72f7723c29/monthly" class="price">£10</a> <a href="#/portal/signup/64ebbbe882217a72f7723c29/monthly" class="price">£20</a></li>
        <li>Annually at <a href="#/portal/signup/64ebbbe882217a72f7723c29/yearly" class="price">£50</a> <a href="#/portal/signup/64ebbbe882217a72f7723c29/yearly" class="price">£100</a> <a href="#/portal/signup/64ebbbe882217a72f7723c29/yearly" class="price">£200</a></li>
        </ul>
</ul>`

You'll need to change the tier codes to match your portal tiers - find them in settings > membership > customize portal > Links (dropdown at the top of the modal), then choose each tier to get the appropriate tier codes.

**Comment by peterfremlin** [comment]
Thanks! This is what I asked for. But it shows me I don't love the solution I proposed :) 

It gives me the idea to make a list of
- £5 per month or £50 per year
...

without need for any buttons.

Maybe the issue is I should give fewer subscription options, or to do something with pull down menus.

Unless you have a bright idea of how to present this more attractively then I'm happy to close this issue and make the list myself.

**Comment by cathysarisky** [comment]
I don't have a better idea than that.  I'll leave the 'price' class in, in case you decide you want it.
